### ISSUE TITLE
Quickcheck test fails quite frequently

### ISSUE THREAD

**Issue by michael-p** [rust-photogrammetry/p3p#5]
Dear all,

I just noticed that the quickcheck test `non_degenerate_case` fails quite frequently, e.g.:
```
running 2 tests
test nordberg::tests::manual_case ... ok
test nordberg::tests::non_degenerate_case ... FAILED

failures:

---- nordberg::tests::non_degenerate_case stdout ----
thread 'nordberg::tests::non_degenerate_case' panicked at '[quickcheck] TEST FAILED. Arguments: ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, 41.0, 0.0), (25.49968, 97.0, 59.0), (38.101242, 91.147705, -97.73874))', /Users/michaelp/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.8.5/src/tester.rs:176:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    nordberg::tests::non_degenerate_case
```
or
```
...
thread 'nordberg::tests::non_degenerate_case' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, 21.0, 0.0), (25.0, 47.0, 61.0), (-86.0, -10.0, 47.0))
Error: "assertion failed: !poses.is_empty()"', /Users/michaelp/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.8.5/src/tester.rs:176:28
...
```
Running tests with `QUICKCHECK_TESTS=10000 cargo test` reliably produces a failure for me on every run.

Best
Michael

**Comment by vadixidav** [comment]
@michael-p I would recommend using the lambda-twist crate in the cv repository. This crate hasn't been kept as up-to-date.

This codebase is the source of that codebase, so its the same but has more fixes.

**Comment by mpizenberg** [comment]
@michael-p indeed, this crate served its purpose but you should follow @vadixidav advice. I haven't taken the time to maintain it, mostly being busy on other things.

**Comment by michael-p** [comment]
@vadixidav Thanks for the heads-up! I already saw that crate and was wondering about the "duplication".

Two things why I checked this one first:
* fewer dependencies: this one only uses `nalgebra` which is pretty common in this field, however, `lambda-twist` also depends on `cv-core` which is fine I guess if one uses more crates from that ecosystem, but we don't. Plus, I'd be using the crate on an embedded system, so am pretty vary of additional dependencies
* repository of `lambda-twist` seems archived? Although it might just be that the link on `crates.io` is outdated

Would you still recommend `lambda-twist` (I see you're the author of that crate, so again, thanks for chiming in, and also for your work on that crate!)

**Comment by michael-p** [comment]
Ok so I went forward and integrated the `lambda-twist` crate in our system (replacing Lepetit's EPnP algorithm for relocalization in a monocular slam system) and everything looks great so far! Thanks again everyone! :)

**Comment by vadixidav** [comment]
@michael-p The lambda-twist in the `cv` mono repo is the right one. The standalone one is now archived because we combined them all into the mono repo. You should be able to pull it from crates.io.
