### ISSUE TITLE
Z-value of `bearing_vectors` unclear

### ISSUE THREAD

**Issue by raphaelmenges** [rust-photogrammetry/p3p#6]
Hello @mpizenberg 👋,

I have a question regarding the `bearing_vectors` as input for the `solve` function in the `nordberg` module. As I understand [the documentation](https://github.com/rust-cv/p3p/blob/0f657e90ff33038415fa7f7331b2ff3f04acf5d0/src/nordberg.rs#L60C81-L60C94), each bearing vector should contain one vertex of the triangle in image-space, i.e., `(u_i, v_i, 1)`. However, in the [test-cases](https://github.com/rust-cv/p3p/blob/0f657e90ff33038415fa7f7331b2ff3f04acf5d0/src/nordberg.rs#L511) the z-values of the `bearing_vectors` are different from 1:

```
let p1_cam = [-0.228_125, -0.061_458_334, 1.0];
let p2_cam = [0.418_75, -0.581_25, 2.0];
let p3_cam = [1.128_125, 0.878_125, 3.0];
```

Moreover, I am confused to read `_cam` or "camera coordinates" in the test-cases and not "image coordinates". Is there a misconception from my side, is the documentation misguiding about z-value or are the test-cases incorrect?

**Comment by mpizenberg** [comment]
Hi, honestly I haven't looked at this code for many years and it's unlikely I can find the time to look into this.

**Comment by vadixidav** [comment]
@raphaelmenges You may also find the most up-to-date version of this code here: https://github.com/rust-cv/cv/blob/main/lambda-twist/src/lib.rs. I don't believe too much has changed, but perhaps it might help.

**Comment by raphaelmenges** [comment]
Thank you for the hint! I have added the crate to my `cargo.toml` as follows:

`cv = { version = "0.6.0", features = ["lambda-twist"] }`

However, cargo then fails to build:

```
Compiling bitarray v0.2.6
   Compiling rusttype v0.9.3
   Compiling spm_precompiled v0.1.4
   Compiling rayon-cond v0.1.0
   Compiling monostate v0.1.9
   Compiling nalgebra v0.18.1
   Compiling eight-point v0.8.0
   Compiling nalgebra v0.30.1
   Compiling matchers v0.1.0
   Compiling image v0.24.6
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/raphael/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitarray-0.2.6/src/lib.rs:2:1
  |
2 | #![feature(min_const_generics)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove the attribute
  |
  = help: the feature `min_const_generics` has been stable since `1.51.0` and no longer requires an attribute to enable

For more information about this error, try `rustc --explain E0554`.
error: could not compile `bitarray` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

I am using `rustc 1.78.0` and `cargo 1.78.0`.

I will further investigate about the initial question of this issue when reading the documentation of `cv` and perhaps create an issue in `cv` about the above problem if it persists!

PS: I understand the test-cases of the other repository better. It looks like the camera-coordinates are used as basis to come up with the bearing vectors, which z-coordinate is 1. See <https://github.com/rust-cv/cv/blob/82a25ee3a88c1200274182951ccd7dfeae4708d2/lambda-twist/tests/consensus.rs#L44>.

**Comment by vadixidav** [comment]
Yes, I have not been putting the time in to keep it maintained. Perhaps it is time to give it an update.
